version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - "3000:80" # Map port 3000 on host to port 80 in the container
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/usr/share/nginx/html
